nginx:
 image: "registry.cn-hangzhou.aliyuncs.com/nginx-phpfpm/nginx-end"
 ports:
  - "80:80"
 links:
  - "phpfpm"
 volumes:
  - ./:/var/www/html/
 container_name: px-backend-nginx

phpfpm:
  image: "registry.cn-hangzhou.aliyuncs.com/phpfpm/phpfpm-end:latest"
  volumes:
   - ./:/var/www/html/
  external_links:
   - "px-mysql:mysql"
  cap_add:
   - SYS_PTRACE
  environment:
   - APP_ENV=dev
  container_name: px-backend-phpfpm
